


const TOURNAMENT_PERMISSIONS = {
    // STAFF
    STAFF: {
        ADD_STAFF: 'ADD_STAFF',
        EDIT_STAFF: 'EDIT_STAFF',
        UPDATE_STAFF_PERMISSIONS: 'UPDATE_STAFF_PERMISSIONS',
        REMOVE_STAFF: 'REMOVE_STAFF',
        STAFF_HISTORY:'STAFF_HISTORY',
    },

    EDIT_SCORETYPE: 'EDIT_SCORETYPE',
    

    // SPORT
    SPORT: {
        CREATE_SPORT: 'CREATE_SPORT',
        EDIT_SPORT: 'EDIT_SPORT',
        VIEW_SPORT: 'VIEW_SPORT',
        DELETE_SPORT: 'DELETE_SPORT',
    },

    // CRUD
    CREATE_TOURNAMENT: 'CREATE_TOURNAMENT',
    ADD_PARTICIPANT: 'ADD_PARTICIPANT',
    REMOVE_PARTICIPANT: 'REMOVE_PARTICIPANT',
    EDIT_TOURNAMENT: 'EDIT_TOURNAMENT',
    VIEW_TOURNAMENTS: 'VIEW_TOURNAMENTS',
    TOURNAMENT_OVERVIEW: 'TOURNAMENT_OVERVIEW',
    ARCHIVE_TOURNAMENT: 'ARCHIVE_TOURNAMENT',
    RESTORE_TOURNAMENT: 'RESTORE_TOURNAMENT',
    DELETE_TOURNAMENT: 'DELETE_TOURNAMENT',
    ANNOUNCE_MATCH_WINNER: 'ANNOUNCE_MATCH_WINNER',

    TOURNAMENT_STATS: 'TOURNAMENT_STATS',

    // VENUE 
    VENUE: {
        ADD: 'ADD',
        EDIT: 'EDIT',
        DELETE: 'DELETE',
        VIEW: 'VIEW'
    },

    // SPONSOR
    SPONSOR: {
        ADD: 'ADD',
        EDIT: 'EDIT',
        DELETE: 'DELETE',
        VIEW: 'VIEW'
    },

    // REFEREE
    REFEREE: {
        ADD: 'ADD',
        EDIT: 'EDIT',
        DELETE: 'DELETE',
        VIEW: 'VIEW'
    },

    // PARTICIPANT
    PARTICIPANT: {

        ADD_PLAYER: 'ADD_PLAYER',
        EDIT_PLAYER: 'EDIT_PLAYER',
        REMOVE_PLAYER: 'REMOVE_PLAYER',
        VIEW_PLAYERS: 'VIEW_PLAYERS',
        VIEW_PLAYER: 'VIEW_PLAYER',

        EDIT_NAME: 'EDIT_NAME',

        EDIT_PARTICIPANT: 'EDIT_PARTICIPANT',
    },

    // MATCH
    MATCH: {
        VIEW_MATCH_STATS: 'VIEW_MATCH_STATS',
        EDIT_MATCH: 'EDIT_MATCH',
        VIEW_MATCH: "VIEW_MATCH",
        UPDATE_SCORE: 'UPDATE_SCORE',
        EDIT_MATCH_SCORETYPE:'EDIT_MATCH_SCORETYPE',
    },

    // ROUND
    ROUND: {
        VIEW_ROUND: 'VIEW_ROUND',
        GAME_FIXTURES: 'GAME_FIXTURES',
        REARRANGE_PARTICIPANT: 'REARRANGE_PARTICIPANT',

        ADD_RR_POINTS: 'ADD_RR_POINTS',
    },

    REWARD: {
        ADD_REWARDS: 'ADD_REWARDS',
        EDIT_REWARD: 'EDIT_REWARD',
        REMOVE_REWARD: 'REMOVE_REWARD',
        VIEW_REWARDS: 'VIEW_REWARDS'
    },

}

const SUB_ADMIN_PERMISSIONS = {

    // TOURNAMENT 
    TOURNAMENT: TOURNAMENT_PERMISSIONS,

    EDIT_SUB_ADMIN_PERMISSIONS: 'EDIT_SUB_ADMIN_PERMISSION',
    CREATE_SUB_ADMIN: 'CREATE_SUB_ADMIN',
    EDIT_SUB_ADMIN: 'EDIT_SUB_ADMIN',
    REMOVE_SUB_ADMIN: 'REMOVE_SUB_ADMIN',
    VIEW_SUB_ADMINS: 'VIEW_SUB_ADMINS',

    SENT_NOTIFICATION: 'SENT_NOTIFICATION',
    VIEW_NOTIFICATION: 'VIEW_NOTIFICATION',
    EDIT_NOTIFICATION: 'VIEW_NOTIFICATION',
    REMOVE_NOTIFICATION: 'VIEW_NOTIFICATION',
};


export {
    SUB_ADMIN_PERMISSIONS,
    TOURNAMENT_PERMISSIONS
}